services:
  nginx:
    image: nginx:latest
    container_name: web
    restart: always
    ports:
      - '6969:80'
    volumes:
      - ./client/web:/usr/share/nginx/html
    networks:
      - network

  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 7070:80
    depends_on:
      - postgres
    networks:
      - network

networks:
  network:
    driver: bridge
